spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/query_engine
    username: postgres
    password: uche1234

  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC

    jwt:
      secret: dev-local-secret-very-strong-123456789