spring:
  application:
    name: query-engine

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    time-zone: UTC

server:
  port: 8080