spring:
  application:
    name: query-engine

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC

server:
  port: 8080

  jwt:
    secret: ${JWT_SECRET:8f92a6d1c6e5b4a32f8c7d6e5a4b3c2d1e0f1a8b7c6d5e4f3a2b1c0d9e8f7a6}
    access-expiration: 900000
    refresh-expiration: 86400000